import type { GearInfo } from "../types";

const GEAR: GearInfo[] = [
  {
    name: "Pole",
    cost: { gp: 0, sp: 5, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 0 },
  },
  {
    name: "Rope, 60'",
    cost: { gp: 1, sp: 0, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 0 },
  },
  {
    name: "Oil, Flask",
    cost: { gp: 0, sp: 5, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 0 },
  },
  {
    name: "Light Spell (Double Range)",
    cost: { gp: 0, sp: 0, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 1 },
  },
  {
    name: "Iron Spikes",
    cost: { gp: 1, sp: 0, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 10, slotsUsed: 1, freeCarry: 0 },
  },
  {
    name: "Flint and Steel",
    cost: { gp: 0, sp: 5, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 0 },
  },
  {
    name: "Mirror",
    cost: { gp: 10, sp: 0, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 0 },
  },
  {
    name: "Rations",
    cost: { gp: 0, sp: 5, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 3, slotsUsed: 1, freeCarry: 0 },
  },
  {
    name: "Crowbar",
    cost: { gp: 0, sp: 5, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 0 },
  },
  {
    name: "Light Spell",
    cost: { gp: 0, sp: 0, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 1 },
  },
  {
    name: "Caltrops",
    cost: { gp: 0, sp: 5, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 0 },
  },
  {
    name: "Flask",
    cost: { gp: 0, sp: 3, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 0 },
  },
  {
    name: "Arrows",
    cost: { gp: 1, sp: 0, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 20, slotsUsed: 1, freeCarry: 0 },
  },
  {
    name: "Bottle",
    cost: { gp: 0, sp: 3, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 0 },
  },
  {
    name: "Grappling Hook",
    cost: { gp: 1, sp: 0, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 0 },
  },
  {
    name: "Crossbow Bolts",
    cost: { gp: 1, sp: 0, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 20, slotsUsed: 1, freeCarry: 0 },
  },
  {
    name: "Lantern",
    cost: { gp: 5, sp: 0, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 0 },
  },
  {
    name: "Thieves' Tools",
    cost: { gp: 0, sp: 0, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 1 },
  },
  {
    name: "Backpack",
    cost: { gp: 2, sp: 0, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 1 },
  },
  {
    name: "Light Spell (Double Time)",
    cost: { gp: 0, sp: 0, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 1 },
  },
  {
    name: "Holy Symbol",
    cost: { gp: 0, sp: 0, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 1 },
  },
  {
    name: "Torch",
    cost: { gp: 0, sp: 5, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 0 },
  },
  {
    name: "Thieving Tools",
    cost: { gp: 0, sp: 0, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 0, freeCarry: 1 },
  },
  {
    name: "Holy Symbol",
    cost: { gp: 0, sp: 0, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 0, freeCarry: 1 },
  },
  {
    name: "Ball bearing",
    cost: { gp: 1, sp: 0, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 0 },
    desc: "A hefty marble of glossy metal. On a DC 12 DEX check, it rolls a near distance along a straight line. It triggers traps as if it were the footfalls of an adult human. Once it triggers a trap, it is lost or destroyed.",
  },
  {
    name: "Candle (3)",
    cost: { gp: 0, sp: 0, cp: 5 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 3, slotsUsed: 1, freeCarry: 0 },
    desc: "Sheds light out to a close distance for 20 minutes of real time. Light can be hidden from outside observation behind a cloak or hand.",
  },
  {
    name: "Charcoal, jar",
    cost: { gp: 1, sp: 0, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 0 },
    desc: "One use. This powder leeches the poison out of an edible item, making it safe.",
  },
  {
    name: "Flash seed",
    cost: { gp: 1, sp: 0, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 0 },
    desc: "A sulfurous seed the size of a peach pit that explodes in a flash of light when it strikes a hard surface. Dark-adapted creatures within near who see it must pass a DC 12 CON check or be blinded for 1 round.",
  },
  {
    name: "Glow paste, jar",
    cost: { gp: 2, sp: 0, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 0 },
    desc: "Five uses of a clear, sticky paste that glows faintly green when exposed to air, leaving a subtle mark. Its dim glow lasts for one day.",
  },
  {
    name: "Holy water, flask",
    cost: { gp: 0, sp: 5, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 0 },
    desc: "The blessed contents of one flask deals 2d4 damage to an undead creature.",
  },
  {
    name: "Lantern hook",
    cost: { gp: 0, sp: 5, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 0 },
    desc: "Connects to a belt and allows the hands-free use of a lantern.",
  },
  {
    name: "Miner's putty, jar",
    cost: { gp: 0, sp: 5, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 0 },
    desc: "A jar with three uses of a tacky brown putty. One glob is strong enough to bond 500 pounds of weight. After use, it dries and flakes off in one day.",
  },
  {
    name: "Net",
    cost: { gp: 0, sp: 5, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 0 },
    desc: "Close range, one target. DC 15 DEX to entrap a creature of human size or smaller. An entangled creature can make a DC 12 DEX check on its turn, escaping on a success.",
  },
  {
    name: "Rope, morzo silk",
    cost: { gp: 50, sp: 0, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 0 },
    desc: "A pencil thin, 60' rope of tough morzo worm silk. It is immune to all damage except from a silvered or magical source.",
  },
  {
    name: "Tallow, jar",
    cost: { gp: 0, sp: 5, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 0 },
    desc: "One application of shiny yellow tallow. It can grease a door-sized object, a person, or close area, making it absurdly slippery. The effect lasts one day.",
  },
  {
    name: "Traveler's lamp",
    cost: { gp: 10, sp: 0, cp: 0 },
    canBeEquipped: false,
    type: "Basic",
    slots: { perSlot: 1, slotsUsed: 1, freeCarry: 0 },
    desc: "Burns one flask of oil a day. Provides enough meager light to see during hex travel in darkness (but not during combat or crawling rounds).",
  },
];

const GEAR_COMPENDIUM: { [name: string]: GearInfo } = {};
for (const g of GEAR) {
  GEAR_COMPENDIUM[g.name.toLowerCase()] = g;
}

export default GEAR_COMPENDIUM;
