import type {
  AdvantageBonus,
  Bonus,
  Class,
  DiceTypeBonus,
  ModifyBonus,
  Talent,
} from "../types";
import { ARMORS } from "./armorCompendium";
import { SPELLS } from "./spellCompendium";
import { WEAPONS } from "./weaponCompendium";

export const CLASS_TALENTS: { [key in Class]: Talent[] } = {
  Fighter: [
    {
      name: "Gain Weapon Mastery with one weapon",
      type: "chooseBonus",
      min: 2,
      max: 2,
      choices: WEAPONS.map(
        (w) =>
          [
            {
              name: `+1 to attack for ${w.name}`,
              desc: `+1 to attack for ${w.name}`,
              type: "modifyAmt",
              bonusAmount: 1,
              bonusTo: "attackRoll",
              bonusSource: "Talent",
              editable: true,
              metadata: {
                type: "weapon",
                weapon: w.name,
              },
            },
            {
              name: `+1 to damage for ${w.name}`,
              desc: `+1 to damage for ${w.name}`,
              type: "modifyAmt",
              bonusAmount: 1,
              bonusTo: "damageRoll",
              bonusSource: "Talent",
              editable: true,
              metadata: {
                type: "weapon",
                weapon: w.name,
              },
            },
          ] as ModifyBonus[],
      ),
    },
    {
      name: "+1 to melee and ranged attacks",
      type: "bonus",
      min: 3,
      max: 7,
      bonuses: [
        {
          name: "+1 to attack type",
          desc: "+1 to melee attacks",
          type: "modifyAmt",
          bonusAmount: 1,
          bonusTo: "attackRoll",
          bonusSource: "Talent",
          editable: true,
          metadata: {
            type: "weaponType",
            weaponType: "Melee",
          },
        },
        {
          name: "+1 to attack type",
          desc: "+1 to ranged attacks",
          type: "modifyAmt",
          bonusAmount: 1,
          bonusTo: "attackRoll",
          bonusSource: "Talent",
          editable: true,
          metadata: {
            type: "weaponType",
            weaponType: "Ranged",
          },
        },
      ] as ModifyBonus[],
    },
    {
      name: "+2 to Strenth, Dexterity, or Constitution stat",
      type: "chooseBonus",
      min: 8,
      max: 9,
      choices: [
        {
          name: "+2 to STR",
          type: "modifyAmt",
          desc: "+2 to STR",
          bonusTo: "stat",
          bonusAmount: 2,
          bonusSource: "Talent",
          editable: true,
          metadata: {
            type: "stat",
            stat: "STR",
          },
        },
        {
          name: "+2 to DEX",
          type: "modifyAmt",
          desc: "+2 to DEX",
          bonusTo: "stat",
          bonusAmount: 2,
          bonusSource: "Talent",
          editable: true,
          metadata: {
            type: "stat",
            stat: "DEX",
          },
        },
        {
          name: "+2 to CON",
          type: "modifyAmt",
          desc: "+2 to CON",
          bonusTo: "stat",
          bonusAmount: 2,
          bonusSource: "Talent",
          editable: true,
          metadata: {
            type: "stat",
            stat: "CON",
          },
        },
      ] as ModifyBonus[],
    },
    {
      name: "Choose one kind of armor. You get +1 AC from that armor",
      type: "chooseBonus",
      min: 10,
      max: 11,
      choices: ARMORS.map(
        (a) =>
          ({
            name: `+1 to ${a.name}`,
            desc: `+1 to ${a.name}`,
            type: "modifyAmt",
            bonusAmount: 1,
            bonusTo: "armorClass",
            bonusSource: "Talent",
            editable: true,
            metadata: {
              type: "armor",
              armor: a.name,
            },
          }) as ModifyBonus,
      ),
    },
  ],
  Priest: [
    {
      name: "Gain advantage on casting one spell you know",
      type: "chooseBonus",
      min: 2,
      max: 2,
      choices: SPELLS.map((s) => ({
        name: `Advantage to cast ${s.name}`,
        desc: `Advantage to cast ${s.name}`,
        type: "advantage",
        bonusTo: "spellcastRoll",
        bonusSource: "Talent",
        editable: true,
        metadata: {
          type: "spell",
          spell: s.name,
        },
      })) as AdvantageBonus[],
    },
    {
      name: "+1 to melee or ranged attacks",
      type: "chooseBonus",
      min: 3,
      max: 6,
      choices: [
        {
          name: "+1 to melee attacks",
          desc: "+1 to melee attacks",
          type: "modifyAmt",
          bonusTo: "attackRoll",
          bonusSource: "Talent",
          bonusAmount: 1,
          editable: true,
          metadata: {
            type: "weaponType",
            weaponType: "Melee",
          },
        },
        {
          name: "+1 to ranged attacks",
          desc: "+1 to ranged attacks",
          type: "modifyAmt",
          bonusTo: "attackRoll",
          bonusSource: "Talent",
          bonusAmount: 1,
          editable: true,
          metadata: {
            type: "weaponType",
            weaponType: "Ranged",
          },
        },
      ] as ModifyBonus[],
    },
    {
      name: "+1 to priest spellcasting checks",
      type: "bonus",
      min: 10,
      max: 11,
      bonuses: [
        {
          name: "+1 to spellcasting",
          desc: "+1 to spellcasting",
          type: "modifyAmt",
          bonusTo: "spellcastRoll",
          bonusAmount: 1,
          bonusSource: "Talent",
          editable: true,
        },
      ] as ModifyBonus[],
    },
    {
      name: "+2 to Strength or Wisdom stat",
      type: "chooseBonus",
      min: 7,
      max: 9,
      choices: [
        {
          name: "+2 to stat",
          type: "modifyAmt",
          desc: "+2 to STR",
          bonusTo: "stat",
          bonusAmount: 2,
          bonusSource: "Talent",
          editable: true,
          metadata: {
            type: "stat",
            stat: "STR",
          },
        },
        {
          name: "+2 to WIS",
          desc: "+2 to WIS",
          type: "modifyAmt",
          bonusTo: "stat",
          bonusAmount: 2,
          bonusSource: "Talent",
          editable: true,
          metadata: {
            type: "stat",
            stat: "WIS",
          },
        },
      ] as ModifyBonus[],
    },
  ],
  Thief: [
    {
      name: "Gain advantage on initiative rolls (reroll if duplicate)",
      type: "bonus",
      min: 2,
      max: 2,
      bonuses: [
        {
          name: "adv initiative",
          desc: "adv initiative rolls",
          type: "advantage",
          bonusTo: "initiativeRoll",
          bonusSource: "Talent",
          editable: true,
        },
      ] as AdvantageBonus[],
    },
    {
      name: "Your Backstab deals +1 dice of damage",
      type: "bonus",
      min: 3,
      max: 6,
      bonuses: [
        {
          name: "+1 backstab dice",
          desc: "+1 backstab dice",
          type: "modifyAmt",
          bonusAmount: 1,
          bonusTo: "backstabDice",
          bonusSource: "Talent",
          editable: true,
        },
      ] as ModifyBonus[],
    },
    {
      name: "+2 to Strength, Dexterity, or Charisma stat",
      type: "chooseBonus",
      min: 7,
      max: 9,
      choices: [
        {
          name: "+2 to STR",
          type: "modifyAmt",
          desc: "+2 to",
          bonusTo: "stat",
          bonusAmount: 2,
          bonusSource: "Talent",
          editable: true,
          metadata: {
            type: "stat",
            stat: "STR",
          },
        },
        {
          name: "+2 to DEX",
          type: "modifyAmt",
          desc: "+2 to DEX",
          bonusTo: "stat",
          bonusAmount: 2,
          bonusSource: "Talent",
          editable: true,
          metadata: {
            type: "stat",
            stat: "DEX",
          },
        },
        {
          name: "+2 to CHA",
          type: "modifyAmt",
          desc: "+2 to CHA",
          bonusTo: "stat",
          bonusAmount: 2,
          bonusSource: "Talent",
          editable: true,
          metadata: {
            type: "stat",
            stat: "CHA",
          },
        },
      ] as ModifyBonus[],
    },
    {
      name: "+1 to melee and ranged attacks",
      type: "bonus",
      min: 10,
      max: 11,
      bonuses: [
        {
          name: "+1 to attack type",
          desc: "+1 to melee attacks",
          type: "modifyAmt",
          bonusAmount: 1,
          bonusTo: "attackRoll",
          bonusSource: "Talent",
          editable: true,
          metadata: {
            type: "weaponType",
            weaponType: "Melee",
          },
        },
        {
          name: "+1 to attack type",
          desc: "+1 to ranged attacks",
          type: "modifyAmt",
          bonusAmount: 1,
          bonusTo: "attackRoll",
          bonusSource: "Talent",
          editable: true,
          metadata: {
            type: "weaponType",
            weaponType: "Ranged",
          },
        },
      ] as ModifyBonus[],
    },
  ],
  Wizard: [
    {
      name: "Make 1 random magic item of a type you choose",
      type: "generic",
      min: 2,
      max: 2,
    },
    {
      name: "+2 to Intelligence stat or +1 to wizard spellcasting checks",
      type: "chooseBonus",
      min: 3,
      max: 7,
      choices: [
        {
          name: "+2 to INT",
          type: "modifyAmt",
          desc: "+2 to INT",
          bonusTo: "stat",
          bonusSource: "Talent",
          bonusAmount: 2,
          editable: true,
          metadata: {
            type: "stat",
            stat: "INT",
          },
        },
        {
          name: "+1 to spellcasting",
          desc: "+1 to spellcasting",
          type: "modifyAmt",
          bonusTo: "spellcastRoll",
          bonusSource: "Talent",
          bonusAmount: 1,
          editable: true,
        },
      ] as ModifyBonus[],
    },
    {
      name: "Gain advantage on casting one spell you know",
      type: "chooseBonus",
      min: 8,
      max: 9,
      choices: SPELLS.map((s) => ({
        name: `Advantage to cast ${s.name}`,
        desc: `Advantage to cast ${s.name}`,
        type: "advantage",
        bonusTo: "spellcastRoll",
        bonusSource: "Talent",
        editable: true,
        metadata: {
          type: "spell",
          spell: s.name,
        },
      })) as AdvantageBonus[],
    },
    {
      name: "Learn one additional wizard spell of any tier you know",
      type: "generic",
      min: 10,
      max: 11,
    },
  ],
  Ranger: [
    {
      type: "chooseBonus",
      min: 2,
      max: 2,
      choices: WEAPONS.map((w) => ({
        name: `d12 damage for ${w.name}`,
        desc: `d12 damage for ${w.name}`,
        type: "diceType",
        bonusTo: "damageRoll",
        bonusSource: "Talent",
        diceType: "d12",
        editable: true,
        metadata: {
          type: "weapon",
          weapon: w.name,
        },
      })) as DiceTypeBonus[],
      name: "You deal d12 damage with one weapon you choose",
    },
    {
      name: "+1 to attacks and damage with melee or ranged weapons",
      type: "chooseBonus",
      min: 3,
      max: 6,
      choices: (["Melee", "Ranged"] as const).map((w) => [
        {
          name: `+1 to attack for ${w} weapons`,
          desc: `+1 to attack for ${w} weapons`,
          type: "modifyAmt",
          bonusAmount: 1,
          bonusTo: "attackRoll",
          bonusSource: "Talent",
          editable: true,
          metadata: {
            type: "weaponType",
            weaponType: w,
          },
        },
        {
          name: `+1 to damage for ${w} weapons`,
          desc: `+1 to damage for ${w} weapons`,
          type: "modifyAmt",
          bonusAmount: 1,
          bonusTo: "damageRoll",
          bonusSource: "Talent",
          editable: true,
          metadata: {
            type: "weaponType",
            weaponType: w,
          },
        },
      ]) as ModifyBonus[][],
    },
    {
      name: "+2 to Strength, Dexterity, or Intelligence stat",
      type: "chooseBonus",
      min: 7,
      max: 9,
      choices: [
        {
          name: "+2 to STR",
          type: "modifyAmt",
          desc: "+2 to",
          bonusTo: "stat",
          bonusAmount: 2,
          bonusSource: "Talent",
          editable: true,
          metadata: {
            type: "stat",
            stat: "STR",
          },
        },
        {
          name: "+2 to DEX",
          type: "modifyAmt",
          desc: "+2 to DEX",
          bonusTo: "stat",
          bonusAmount: 2,
          bonusSource: "Talent",
          editable: true,
          metadata: {
            type: "stat",
            stat: "DEX",
          },
        },
        {
          name: "+2 to INT",
          type: "modifyAmt",
          desc: "+2 to INT",
          bonusTo: "stat",
          bonusAmount: 2,
          bonusSource: "Talent",
          editable: true,
          metadata: {
            type: "stat",
            stat: "INT",
          },
        },
      ] as ModifyBonus[],
    },
    {
      name: "You gain ADV on Herbalism checks for a remedy you choose",
      type: "generic",
      min: 10,
      max: 11,
    },
  ],
  Bard: [
    {
      name: "You find a random priest or wizard wand (you choose)",
      type: "generic",
      min: 2,
      max: 2,
    },
    {
      name: "+1 to melee and ranged attacks or +1 to Magical Dabbler rolls",
      type: "chooseBonus",
      min: 3,
      max: 6,
      choices: [
        [
          {
            name: "+1 to melee attacks",
            desc: "+1 to melee attacks",
            type: "modifyAmt",
            bonusTo: "attackRoll",
            bonusSource: "Talent",
            bonusAmount: 1,
            editable: true,
            metadata: { type: "weaponType", weaponType: "Melee" },
          },
          {
            name: "+1 to ranged attacks",
            desc: "+1 to ranged attacks",
            type: "modifyAmt",
            bonusTo: "attackRoll",
            bonusSource: "Talent",
            bonusAmount: 1,
            editable: true,
            metadata: { type: "weaponType", weaponType: "Ranged" },
          },
        ],
        [
          {
            name: "+1 to Magical Dabbler rolls",
            desc: "+1 to Magical Dabbler rolls",
            type: "modifyAmt",
            bonusTo: "spellcastRoll",
            bonusSource: "Talent",
            bonusAmount: 1,
            editable: true,
          },
        ],
      ] as (Bonus | Bonus[])[],
    },
    {
      name: "+2 points to distribute to any stats",
      type: "chooseBonus",
      min: 7,
      max: 9,
      choices: [
        {
          name: "+2 to STR",
          type: "modifyAmt",
          desc: "+2 to STR",
          bonusTo: "stat",
          bonusAmount: 2,
          bonusSource: "Talent",
          editable: true,
          metadata: { type: "stat", stat: "STR" },
        },
        {
          name: "+2 to DEX",
          type: "modifyAmt",
          desc: "+2 to DEX",
          bonusTo: "stat",
          bonusAmount: 2,
          bonusSource: "Talent",
          editable: true,
          metadata: { type: "stat", stat: "DEX" },
        },
        {
          name: "+2 to CON",
          type: "modifyAmt",
          desc: "+2 to CON",
          bonusTo: "stat",
          bonusAmount: 2,
          bonusSource: "Talent",
          editable: true,
          metadata: { type: "stat", stat: "CON" },
        },
        {
          name: "+2 to INT",
          type: "modifyAmt",
          desc: "+2 to INT",
          bonusTo: "stat",
          bonusAmount: 2,
          bonusSource: "Talent",
          editable: true,
          metadata: { type: "stat", stat: "INT" },
        },
        {
          name: "+2 to WIS",
          type: "modifyAmt",
          desc: "+2 to WIS",
          bonusTo: "stat",
          bonusAmount: 2,
          bonusSource: "Talent",
          editable: true,
          metadata: { type: "stat", stat: "WIS" },
        },
        {
          name: "+2 to CHA",
          type: "modifyAmt",
          desc: "+2 to CHA",
          bonusTo: "stat",
          bonusAmount: 2,
          bonusSource: "Talent",
          editable: true,
          metadata: { type: "stat", stat: "CHA" },
        },
      ] as ModifyBonus[],
    },
    {
      name: "Your Presence effects become DC 9 to enact",
      type: "generic",
      min: 10,
      max: 11,
    },
  ],
  "Knight of St. Ydris": [
    {
      name: "Your Demonic Possession bonus increases by 1 point",
      type: "generic",
      min: 2,
      max: 2,
    },
    {
      name: "+1 to melee or ranged attacks",
      type: "chooseBonus",
      min: 3,
      max: 6,
      choices: [
        {
          name: "+1 to melee attacks",
          desc: "+1 to melee attacks",
          type: "modifyAmt",
          bonusTo: "attackRoll",
          bonusSource: "Talent",
          bonusAmount: 1,
          editable: true,
          metadata: { type: "weaponType", weaponType: "Melee" },
        },
        {
          name: "+1 to ranged attacks",
          desc: "+1 to ranged attacks",
          type: "modifyAmt",
          bonusTo: "attackRoll",
          bonusSource: "Talent",
          bonusAmount: 1,
          editable: true,
          metadata: { type: "weaponType", weaponType: "Ranged" },
        },
      ] as ModifyBonus[],
    },
    {
      name: "+2 to Strength, Dexterity, or Constitution stat",
      type: "chooseBonus",
      min: 7,
      max: 9,
      choices: [
        {
          name: "+2 to STR",
          type: "modifyAmt",
          desc: "+2 to STR",
          bonusTo: "stat",
          bonusAmount: 2,
          bonusSource: "Talent",
          editable: true,
          metadata: { type: "stat", stat: "STR" },
        },
        {
          name: "+2 to DEX",
          type: "modifyAmt",
          desc: "+2 to DEX",
          bonusTo: "stat",
          bonusAmount: 2,
          bonusSource: "Talent",
          editable: true,
          metadata: { type: "stat", stat: "DEX" },
        },
        {
          name: "+2 to CON",
          type: "modifyAmt",
          desc: "+2 to CON",
          bonusTo: "stat",
          bonusAmount: 2,
          bonusSource: "Talent",
          editable: true,
          metadata: { type: "stat", stat: "CON" },
        },
      ] as ModifyBonus[],
    },
    {
      name: "+2 to Charisma stat or +1 to witch spellcasting checks",
      type: "chooseBonus",
      min: 10,
      max: 11,
      choices: [
        {
          name: "+2 to CHA",
          type: "modifyAmt",
          desc: "+2 to CHA",
          bonusTo: "stat",
          bonusAmount: 2,
          bonusSource: "Talent",
          editable: true,
          metadata: { type: "stat", stat: "CHA" },
        },
        {
          name: "+1 to witch spellcasting",
          desc: "+1 to witch spellcasting checks",
          type: "modifyAmt",
          bonusTo: "spellcastRoll",
          bonusSource: "Talent",
          bonusAmount: 1,
          editable: true,
        },
      ] as ModifyBonus[],
    },
  ],
  Warlock: [
    {
      name: "Roll a Patron Boon from any patron; an unexplained gift",
      type: "generic",
      min: 2,
      max: 2,
    },
    {
      name: "Add +1 point to two stats (they must be different)",
      type: "chooseBonus",
      min: 3,
      max: 6,
      choices: [
        // Represent as choices for stat modifications
        {
          name: "+1 to STR",
          type: "modifyAmt",
          desc: "+1 to STR",
          bonusTo: "stat",
          bonusAmount: 1,
          bonusSource: "Talent",
          editable: true,
          metadata: { type: "stat", stat: "STR" },
        },
        {
          name: "+1 to DEX",
          type: "modifyAmt",
          desc: "+1 to DEX",
          bonusTo: "stat",
          bonusAmount: 1,
          bonusSource: "Talent",
          editable: true,
          metadata: { type: "stat", stat: "DEX" },
        },
        {
          name: "+1 to CON",
          type: "modifyAmt",
          desc: "+1 to CON",
          bonusTo: "stat",
          bonusAmount: 1,
          bonusSource: "Talent",
          editable: true,
          metadata: { type: "stat", stat: "CON" },
        },
        {
          name: "+1 to INT",
          type: "modifyAmt",
          desc: "+1 to INT",
          bonusTo: "stat",
          bonusAmount: 1,
          bonusSource: "Talent",
          editable: true,
          metadata: { type: "stat", stat: "INT" },
        },
        {
          name: "+1 to WIS",
          type: "modifyAmt",
          desc: "+1 to WIS",
          bonusTo: "stat",
          bonusAmount: 1,
          bonusSource: "Talent",
          editable: true,
          metadata: { type: "stat", stat: "WIS" },
        },
        {
          name: "+1 to CHA",
          type: "modifyAmt",
          desc: "+1 to CHA",
          bonusTo: "stat",
          bonusAmount: 1,
          bonusSource: "Talent",
          editable: true,
          metadata: { type: "stat", stat: "CHA" },
        },
      ] as ModifyBonus[],
    },
    {
      name: "+1 to melee or ranged attacks",
      type: "chooseBonus",
      min: 7,
      max: 9,
      choices: [
        {
          name: "+1 to melee attacks",
          desc: "+1 to melee attacks",
          type: "modifyAmt",
          bonusTo: "attackRoll",
          bonusSource: "Talent",
          bonusAmount: 1,
          editable: true,
          metadata: { type: "weaponType", weaponType: "Melee" },
        },
        {
          name: "+1 to ranged attacks",
          desc: "+1 to ranged attacks",
          type: "modifyAmt",
          bonusTo: "attackRoll",
          bonusSource: "Talent",
          bonusAmount: 1,
          editable: true,
          metadata: { type: "weaponType", weaponType: "Ranged" },
        },
      ] as ModifyBonus[],
    },
    {
      name: "Roll two Patron Boons and choose one to keep",
      type: "generic",
      min: 10,
      max: 11,
    },
  ],
  Witch: [
    {
      name: "1/day, teleport to your familiar's location as a move",
      type: "generic",
      min: 2,
      max: 2,
    },
    {
      name: "+2 to Charisma stat or +1 to witch spellcasting checks",
      type: "chooseBonus",
      min: 3,
      max: 7,
      choices: [
        {
          name: "+2 to CHA",
          type: "modifyAmt",
          desc: "+2 to CHA",
          bonusTo: "stat",
          bonusAmount: 2,
          bonusSource: "Talent",
          editable: true,
          metadata: { type: "stat", stat: "CHA" },
        },
        {
          name: "+1 to witch spellcasting",
          desc: "+1 to witch spellcasting checks",
          type: "modifyAmt",
          bonusTo: "spellcastRoll",
          bonusSource: "Talent",
          bonusAmount: 1,
          editable: true,
        },
      ] as ModifyBonus[],
    },
    {
      name: "Gain advantage on casting one spell you know",
      type: "chooseBonus",
      min: 8,
      max: 9,
      choices: SPELLS.map((s) => ({
        name: `Advantage to cast ${s.name}`,
        desc: `Advantage to cast ${s.name}`,
        type: "advantage",
        bonusTo: "spellcastRoll",
        bonusSource: "Talent",
        editable: true,
        metadata: {
          type: "spell",
          spell: s.name,
        },
      })) as AdvantageBonus[],
    },
    {
      name: "Learn an additional witch spell of any tier you can cast",
      type: "generic",
      min: 10,
      max: 11,
    },
  ],
  "Desert Rider": [
    {
      name: "You can use any rider-bearing creature as your mount",
      type: "generic",
      min: 2,
      max: 2,
    },
    {
      name: "You gain +1 to attacks or damage",
      type: "chooseBonus",
      min: 3,
      max: 6,
      choices: [
        {
          name: "+1 to melee/ranged attacks",
          desc: "+1 to attacks",
          type: "modifyAmt",
          bonusTo: "attackRoll",
          bonusSource: "Talent",
          bonusAmount: 1,
          editable: true,
        },
        {
          name: "+1 to weapon damage",
          desc: "+1 to damage",
          type: "modifyAmt",
          bonusTo: "damageRoll",
          bonusSource: "Talent",
          bonusAmount: 1,
          editable: true,
        },
      ] as ModifyBonus[],
    },
    {
      name: "+2 to Strength or Dexterity stat, or +1 to melee attacks",
      type: "chooseBonus",
      min: 7,
      max: 9,
      choices: [
        {
          name: "+2 to STR",
          type: "modifyAmt",
          desc: "+2 to STR",
          bonusTo: "stat",
          bonusAmount: 2,
          bonusSource: "Talent",
          editable: true,
          metadata: { type: "stat", stat: "STR" },
        },
        {
          name: "+2 to DEX",
          type: "modifyAmt",
          desc: "+2 to DEX",
          bonusTo: "stat",
          bonusAmount: 2,
          bonusSource: "Talent",
          editable: true,
          metadata: { type: "stat", stat: "DEX" },
        },
        {
          name: "+1 to melee attacks",
          desc: "+1 to melee attacks",
          type: "modifyAmt",
          bonusTo: "attackRoll",
          bonusSource: "Talent",
          bonusAmount: 1,
          editable: true,
          metadata: { type: "weaponType", weaponType: "Melee" },
        },
      ] as ModifyBonus[],
    },
    {
      name: "Gain an additional use of your Charge talent each day",
      type: "generic",
      min: 10,
      max: 11,
    },
  ],
  "Pit Fighter": [
    {
      name: "1/day, ignore all damage and effects from one attack",
      type: "generic",
      min: 2,
      max: 2,
    },
    {
      name: "You gain +1 to melee weapon damage",
      type: "bonus",
      min: 3,
      max: 6,
      bonuses: [
        {
          name: "+1 to melee damage",
          desc: "+1 to melee damage",
          type: "modifyAmt",
          bonusTo: "damageRoll",
          bonusSource: "Talent",
          bonusAmount: 1,
          editable: true,
          metadata: { type: "weaponType", weaponType: "Melee" },
        },
      ] as ModifyBonus[],
    },
    {
      name: "+2 to Strength or Constitution stat, or +1 to melee attacks",
      type: "chooseBonus",
      min: 7,
      max: 9,
      choices: [
        {
          name: "+2 to STR",
          type: "modifyAmt",
          desc: "+2 to STR",
          bonusTo: "stat",
          bonusAmount: 2,
          bonusSource: "Talent",
          editable: true,
          metadata: { type: "stat", stat: "STR" },
        },
        {
          name: "+2 to CON",
          type: "modifyAmt",
          desc: "+2 to CON",
          bonusTo: "stat",
          bonusAmount: 2,
          bonusSource: "Talent",
          editable: true,
          metadata: { type: "stat", stat: "CON" },
        },
        {
          name: "+1 to melee attacks",
          desc: "+1 to melee attacks",
          type: "modifyAmt",
          bonusTo: "attackRoll",
          bonusSource: "Talent",
          bonusAmount: 1,
          editable: true,
          metadata: { type: "weaponType", weaponType: "Melee" },
        },
      ] as ModifyBonus[],
    },
    {
      name: "Increase the HP you gain from Flourish by 1d6",
      type: "generic",
      min: 10,
      max: 11,
    },
  ],
  "Ras-Godai": [
    {
      name: "You are trained in the use of poisons",
      type: "generic",
      min: 2,
      max: 2,
    },
    {
      name: "Roll an additional talent on the Black Lotus Talents table",
      type: "generic",
      min: 3,
      max: 6,
    },
    {
      name: "+2 to Strength or Dexterity stat, or +1 to melee attacks",
      type: "chooseBonus",
      min: 7,
      max: 9,
      choices: [
        {
          name: "+2 to STR",
          type: "modifyAmt",
          desc: "+2 to STR",
          bonusTo: "stat",
          bonusAmount: 2,
          bonusSource: "Talent",
          editable: true,
          metadata: { type: "stat", stat: "STR" },
        },
        {
          name: "+2 to DEX",
          type: "modifyAmt",
          desc: "+2 to DEX",
          bonusTo: "stat",
          bonusAmount: 2,
          bonusSource: "Talent",
          editable: true,
          metadata: { type: "stat", stat: "DEX" },
        },
        {
          name: "+1 to melee attacks",
          desc: "+1 to melee attacks",
          type: "modifyAmt",
          bonusTo: "attackRoll",
          bonusSource: "Talent",
          bonusAmount: 1,
          editable: true,
          metadata: { type: "weaponType", weaponType: "Melee" },
        },
      ] as ModifyBonus[],
    },
    {
      name: "Gain an additional use of your Smoke Step talent",
      type: "generic",
      min: 10,
      max: 11,
    },
  ],
  "Sea Wolf": [
    {
      name: "1/day, go berserk: immune to damage for 3 rounds",
      type: "generic",
      min: 2,
      max: 2,
    },
    {
      name: "Your attacks deal +1 damage",
      type: "bonus",
      min: 3,
      max: 6,
      bonuses: [
        {
          name: "+1 to damage",
          desc: "+1 to damage",
          type: "modifyAmt",
          bonusTo: "damageRoll",
          bonusSource: "Talent",
          bonusAmount: 1,
          editable: true,
        },
      ] as ModifyBonus[],
    },
    {
      name: "+2 to Strength or Constitution stat, or +1 to attacks",
      type: "chooseBonus",
      min: 7,
      max: 9,
      choices: [
        {
          name: "+2 to STR",
          type: "modifyAmt",
          desc: "+2 to STR",
          bonusTo: "stat",
          bonusAmount: 2,
          bonusSource: "Talent",
          editable: true,
          metadata: { type: "stat", stat: "STR" },
        },
        {
          name: "+2 to CON",
          type: "modifyAmt",
          desc: "+2 to CON",
          bonusTo: "stat",
          bonusAmount: 2,
          bonusSource: "Talent",
          editable: true,
          metadata: { type: "stat", stat: "CON" },
        },
        {
          name: "+1 to attacks",
          desc: "+1 to attacks",
          type: "modifyAmt",
          bonusTo: "attackRoll",
          bonusSource: "Talent",
          bonusAmount: 1,
          editable: true,
        },
      ] as ModifyBonus[],
    },
    {
      name: "Duality; choose two different Old Gods effects each day",
      type: "generic",
      min: 10,
      max: 11,
    },
  ],
  Seer: [
    {
      name: "Learn an additional seer spell from any tier you can cast",
      type: "generic",
      min: 2,
      max: 2,
    },
    {
      name: "Gain an additional use of your Omen talent each day",
      type: "generic",
      min: 3,
      max: 6,
    },
    {
      name: "+2 to WIS or CHA stat, or +1 to spellcasting checks",
      type: "chooseBonus",
      min: 7,
      max: 9,
      choices: [
        {
          name: "+2 to WIS",
          type: "modifyAmt",
          desc: "+2 to WIS",
          bonusTo: "stat",
          bonusAmount: 2,
          bonusSource: "Talent",
          editable: true,
          metadata: { type: "stat", stat: "WIS" },
        },
        {
          name: "+2 to CHA",
          type: "modifyAmt",
          desc: "+2 to CHA",
          bonusTo: "stat",
          bonusAmount: 2,
          bonusSource: "Talent",
          editable: true,
          metadata: { type: "stat", stat: "CHA" },
        },
        {
          name: "+1 to spellcasting",
          desc: "+1 to spellcasting checks",
          type: "modifyAmt",
          bonusTo: "spellcastRoll",
          bonusSource: "Talent",
          bonusAmount: 1,
          editable: true,
        },
      ] as ModifyBonus[],
    },
    {
      name: "Increase the die category of your Destined talent by one",
      type: "generic",
      min: 10,
      max: 11,
    },
  ],
};
